Blog app - setup and controllers
KingsleyIbe/blog-app pull request #1
Opened 2022-03-23 09:06 UTC by KingsleyIbe

## Milestone changes

### In this milestone, I implemented the following:
- Created a new app "blog-app"
- Then Initialized the app with Git.
- Ensured that the project has Postgres database set up.
- For each URL I created:
      - A route.
      - An action in the correct controller.
      - A view file.
- Ensured View files include only placeholders written in plain HTML,
- Added code to handle only the 4 required URLs.

2022-03-23 09:33 UTC, hiromataba requested changes
Hi @KingsleyIbe   :wave: :wave: ,

![almost-there](https://user-images.githubusercontent.com/75126481/159551739-33624f46-aea0-4e83-9068-b2f4b5cc1042.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
### To highlight :medal_military: 
- No linter errors :heavy_check_mark: 
- Your app is working :heavy_check_mark: 
- Nice commit history :heavy_check_mark: 

## Required Changes ♻️

- [x] Please update your README file with the correct information to make your project more professional, Kindly check out [this template](https://github.com/microverseinc/readme-template) and update yours

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 09:33 UTC, hiromataba commented on Gemfile
> +gem 'sqlite3', '~> 1.4'
- [ ] You should use Postgres as db not the default ssqlite3, using Postgres will help you when deploying your app, It is going to be something like this :point_down: 

```ruby
...

default: &default
  adapter: postgresql
  encoding: unicode

...
```

2022-03-23 09:33 UTC, hiromataba commented on config/routes.rb
>    # root "articles#index"
- [ ] [OPTIONAL] You did great adding the routes but I think it would be better  to use resources and get less code, have a look at this :point_down: 

```ruby
 resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end
```

2022-03-23 09:40 UTC, KingsleyIbe commented on config/routes.rb
>    # root "articles#index"
Hey @hiromataba 

Thank you for your prompt review.
Changes will be implemented accordingly.

2022-03-23 10:57 UTC, dasileker requested changes
### **Hi @KingsleyIbe,** 

### **Great work on making the changes 👏** 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## **Suggested changes**
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-03-23 10:57 UTC, dasileker commented on Gemfile
>  # The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
- [ ] Nice on updating the database to `PostgreSQL` however you have forgotten to add the `pg` gem in your gemfile. it's necessary because we need to create and migrate the data.

2022-03-23 11:42 UTC, uwadonat approved these changes
Hi **@[KingsleyIbe](https://github.com/KingsleyIbe),** 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-23 11:43 UTC, KingsleyIbe commented
@uwadonat 

Thanks for your prompt response and for approving the project.

2022-03-23 11:43 UTC, merged

2022-03-24 10:37 UTC, hiromataba commented on config/routes.rb
>    # root "articles#index"
You are welcome @KingsleyIbe :wink: